<?php

use Illuminate\Database\Seeder;

class CategoryVendorTypeTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('category_vendor_type')->insert([

			['vendor_type_id'=>'1', 'category_id'=>'1'],
			['vendor_type_id'=>'2', 'category_id'=>'1'],
			['vendor_type_id'=>'3', 'category_id'=>'1'],
			['vendor_type_id'=>'4', 'category_id'=>'1'],
			['vendor_type_id'=>'5', 'category_id'=>'1'],
			['vendor_type_id'=>'6', 'category_id'=>'1'],
			['vendor_type_id'=>'7', 'category_id'=>'1'],
			['vendor_type_id'=>'8', 'category_id'=>'1'],
			['vendor_type_id'=>'9', 'category_id'=>'1'],
			['vendor_type_id'=>'10', 'category_id'=>'1'],
			['vendor_type_id'=>'11', 'category_id'=>'1'],
			['vendor_type_id'=>'12', 'category_id'=>'1'],
			['vendor_type_id'=>'13', 'category_id'=>'1'],
			['vendor_type_id'=>'14', 'category_id'=>'1'],
			['vendor_type_id'=>'15', 'category_id'=>'1'],
			['vendor_type_id'=>'16', 'category_id'=>'1'],
			['vendor_type_id'=>'17', 'category_id'=>'1'],
			['vendor_type_id'=>'18', 'category_id'=>'1'],
			['vendor_type_id'=>'19', 'category_id'=>'1'],
			['vendor_type_id'=>'20', 'category_id'=>'1'],

			['vendor_type_id'=> '1', 'category_id' => '2'], 
			['vendor_type_id'=> '2', 'category_id' => '2'], 
			['vendor_type_id'=> '3', 'category_id' => '2'], 
			['vendor_type_id'=> '4', 'category_id' => '2'], 
			['vendor_type_id'=> '5', 'category_id' => '2'], 
			['vendor_type_id'=> '11', 'category_id' => '2'], 
			['vendor_type_id'=> '13', 'category_id' => '2'], 
			['vendor_type_id'=> '9', 'category_id' => '2'], 
			['vendor_type_id'=> '10', 'category_id' => '2'], 
			['vendor_type_id'=> '12', 'category_id' => '2'], 
			['vendor_type_id'=> '14', 'category_id' => '2'], 
			['vendor_type_id'=> '15', 'category_id' => '2'], 
			['vendor_type_id'=> '16', 'category_id' => '2'], 
			['vendor_type_id'=> '21', 'category_id' => '2'], 
			['vendor_type_id'=> '18', 'category_id' => '2'], 
			['vendor_type_id'=> '19', 'category_id' => '2'], 
			['vendor_type_id'=> '20', 'category_id' => '2'], 


			['vendor_type_id'=>'1', 'category_id' => '3'], 
			['vendor_type_id'=>'2', 'category_id' => '3'], 
			['vendor_type_id'=>'3', 'category_id' => '3'], 
			['vendor_type_id'=>'4', 'category_id' => '3'], 
			['vendor_type_id'=>'5', 'category_id' => '3'], 
			['vendor_type_id'=>'6', 'category_id' => '3'], 
			['vendor_type_id'=>'9', 'category_id' => '3'], 
			['vendor_type_id'=>'10', 'category_id' => '3'], 
			['vendor_type_id'=>'11', 'category_id' => '3'], 
			['vendor_type_id'=>'13', 'category_id' => '3'], 
			['vendor_type_id'=>'12', 'category_id' => '3'], 
			['vendor_type_id'=>'14', 'category_id' => '3'], 
			['vendor_type_id'=>'15', 'category_id' => '3'], 
			['vendor_type_id'=>'16', 'category_id' => '3'], 
			['vendor_type_id'=>'21', 'category_id' => '3'], 
			['vendor_type_id'=>'18', 'category_id' => '3'], 
			['vendor_type_id'=>'19', 'category_id' => '3'], 
			['vendor_type_id'=>'20', 'category_id' => '3'],

			['vendor_type_id'=>'1', 'category_id' => '4'], 
			['vendor_type_id'=>'2', 'category_id' => '4'], 
			['vendor_type_id'=>'3', 'category_id' => '4'], 
			['vendor_type_id'=>'4', 'category_id' => '4'], 
			['vendor_type_id'=>'5', 'category_id' => '4'], 
			['vendor_type_id'=>'6', 'category_id' => '4'], 
			['vendor_type_id'=>'22', 'category_id' => '4'], 
			['vendor_type_id'=>'9', 'category_id' => '4'], 
			['vendor_type_id'=>'10', 'category_id' => '4'], 
			['vendor_type_id'=>'11', 'category_id' => '4'], 
			['vendor_type_id'=>'13', 'category_id' => '4'], 
			['vendor_type_id'=>'12', 'category_id' => '4'], 
			['vendor_type_id'=>'14', 'category_id' => '4'], 
			['vendor_type_id'=>'15', 'category_id' => '4'], 
			['vendor_type_id'=>'16', 'category_id' => '4'], 
			['vendor_type_id'=>'21', 'category_id' => '4'], 
			['vendor_type_id'=>'18', 'category_id' => '4'], 
			['vendor_type_id'=>'19', 'category_id' => '4'], 
			['vendor_type_id'=>'20', 'category_id' => '4'], 

			['vendor_type_id' => '1', 'category_id' => '5'],  
			['vendor_type_id' => '2', 'category_id' => '5'],  
			['vendor_type_id' => '3', 'category_id' => '5'],  
			['vendor_type_id' => '4', 'category_id' => '5'],  
			['vendor_type_id' => '5', 'category_id' => '5'],  
			['vendor_type_id' => '6', 'category_id' => '5'],  
			['vendor_type_id' => '23', 'category_id' => '5'],  
			['vendor_type_id' => '9', 'category_id' => '5'],  
			['vendor_type_id' => '10', 'category_id' => '5'],  
			['vendor_type_id' => '11', 'category_id' => '5'],  
			['vendor_type_id' => '13', 'category_id' => '5'],  
			['vendor_type_id' => '12', 'category_id' => '5'],  
			['vendor_type_id' => '14', 'category_id' => '5'],  
			['vendor_type_id' => '15', 'category_id' => '5'],  
			['vendor_type_id' => '16', 'category_id' => '5'],  
			['vendor_type_id' => '21', 'category_id' => '5'],  
			['vendor_type_id' => '18', 'category_id' => '5'],  
			['vendor_type_id' => '19', 'category_id' => '5'],  
			['vendor_type_id' => '20', 'category_id' => '5'],

			['vendor_type_id' => '1' , 'category_id' => '6'],
			['vendor_type_id' => '2' , 'category_id' => '6'],
			['vendor_type_id' => '3' , 'category_id' => '6'],
			['vendor_type_id' => '4' , 'category_id' => '6'],
			['vendor_type_id' => '5' , 'category_id' => '6'],
			['vendor_type_id' => '6' , 'category_id' => '6'],
			['vendor_type_id' => '24' , 'category_id' => '6'],
			['vendor_type_id' => '9' , 'category_id' => '6'],
			['vendor_type_id' => '10' , 'category_id' => '6'],
			['vendor_type_id' => '11' , 'category_id' => '6'],
			['vendor_type_id' => '12' , 'category_id' => '6'],
			['vendor_type_id' => '13' , 'category_id' => '6'],
			['vendor_type_id' => '14' , 'category_id' => '6'],
			['vendor_type_id' => '15' , 'category_id' => '6'],
			['vendor_type_id' => '16' , 'category_id' => '6'],
			['vendor_type_id' => '21' , 'category_id' => '6'],
			['vendor_type_id' => '18' , 'category_id' => '6'],
			['vendor_type_id' => '19' , 'category_id' => '6'],
			['vendor_type_id' => '20' , 'category_id' => '6'],
        ]);
    }
}
